# Generated by Django 4.1.2 on 2023-01-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Koordinat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_penyu", models.CharField(max_length=100)),
                ("alamat", models.CharField(max_length=100)),
                ("koordinat", models.CharField(max_length=100)),
            ],
        ),
    ]
