# Generated by Django 4.1.2 on 2023-01-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("penyu1_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Klasifikasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_ilmiah", models.TextField(null=True)),
                ("nama_lokal", models.CharField(max_length=100, null=True)),
                ("spesies", models.CharField(max_length=20)),
                ("img", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="koordinat",
            name="nama_penyu",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
