# Generated by Django 4.1.2 on 2023-01-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penyu1_app', '0002_klasifikasi_user_alter_koordinat_nama_penyu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
